// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 환경 변수에서 직접 가져오기 (fallback 없음)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// 환경 변수 검증 (경고만 표시, throw 없음)
if (typeof window !== 'undefined') {
  if (!SUPABASE_URL) {
    console.warn('⚠️ VITE_SUPABASE_URL이 설정되지 않았습니다. Supabase 기능이 작동하지 않을 수 있습니다.');
  }
  if (!SUPABASE_ANON_KEY) {
    console.warn('⚠️ VITE_SUPABASE_PUBLISHABLE_KEY가 설정되지 않았습니다. Supabase 기능이 작동하지 않을 수 있습니다.');
  }
  if (SUPABASE_URL && SUPABASE_ANON_KEY) {
    console.log('✅ Supabase 환경 변수 로드됨');
  }
}

// Supabase client 생성 (환경 변수가 없어도 생성, 실제 사용 시 에러 발생)
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY
);